### ISSUE TITLE
Missing project documents

### ISSUE THREAD

**Issue by zengkaiya** [Ying1123/llm-caching-multiplexing#1]
Dear author,  your project missing/data/lambda_ opt_ flops_ clean_ train.json file, so thar the run_exp.py file of the inferband directory can't finish.
<img width="460" alt="屏幕截图 2023-09-06 104621" src="https://github.com/Ying1123/llm-caching-multiplexing/assets/122162961/e941c454-16c0-42b2-a05c-a84bc52abd46">

**Comment by SyhFighting** [comment]
Hi, how did you solve this problem? @zengkaiya
